---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: chat
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 8081
              name: admin
          readinessProbe:
            httpGet:
              path: /check
              port: http
          livenessProbe:
            httpGet:
              path: /healthz
              port: admin
            initialDelaySeconds: 30
