---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: multiregion-chat-experiment
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 8081
              name: admin
          readinessProbe:
            httpGet:
              path: /check
              port: http
          livenessProbe:
            httpGet:
              path: /healthz
              port: admin
            initialDelaySeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
# apiVersion: policy/v1beta1
# kind: PodDisruptionBudget
# metadata:
#   name: api
# spec:
#   maxUnavailable: 1
#   selector:
#     matchLabels:
#       app: api
# ---
# apiVersion: "traefik.containo.us/v1alpha1"
# kind: "Middleware"
# metadata:
#   name: api
# spec:
#   headers:
#     forceSTSHeader: true
#     stsSeconds: 31536000
#     stsIncludeSubdomains: true
#     stsPreload: true
#     referrerPolicy: "no-referrer-when-downgrade"
#     contentTypeNosniff: true
#     contentSecurityPolicy: "upgrade-insecure-requests"
#     browserXssFilter: true
#     customFrameOptionsValue: "SAMEORIGIN"
#     customResponseHeaders:
#       "Permissions-Policy": "geolocation=(); midi=(); notifications=(); push=(); sync-xhr=(); microphone=(); camera=(); magnetometer=(); gyroscope=(); speaker=(self); vibrate=(); fullscreen=(self); payment=();"
# ---
# apiVersion: "traefik.containo.us/v1alpha1"
# kind: "IngressRoute"
# metadata:
#   name: api
# spec:
#   entryPoints: ["websecure"]
#   routes:
#     - match: "Host(`www.aaronbatilo.dev`) && PathPrefix(`/`)"
#       kind: "Rule"
#       middlewares:
#         - name: api
#       services:
#         - name: api
#           port: 80
