name: Update pulumi stack
on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
      - main

jobs:
  pulumi:
    name: Run pulumi
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      AWS_ROLE_ARN: arn:aws:iam::717012417639:role/srv_ops
      AWS_WEB_IDENTITY_TOKEN_FILE: /tmp/awscreds
      AWS_DEFAULT_REGION: us-west-2
    steps:
      - uses: actions/checkout@v2

      - name: Install asdf
        uses: asdf-vm/actions/setup@v1
      - name: Install asdf tools
        run: |
          ./asdf.sh

      - name: assume role
        run: |
          curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sigstore" | jq -r '.value' > $AWS_WEB_IDENTITY_TOKEN_FILE

      - name: Login to EKS
        run: |
          aws eks update-kubeconfig --name usw2-r

      - uses: docker/setup-buildx-action@v1
        with:
          install: true
          driver: kubernetes
          driver-opts: |
            replicas=1
            namespace=buildx
            requests.cpu=1
            requests.memory=1Gi
            limits.cpu=1.5
            requests.memory=2Gi

      - name: Initialize pulumi dependencies
        working-directory: deployments/pulumi
        run: |
          npm ci

      - uses: pulumi/actions@v3
        if: github.event_name == 'pull_request'
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        with:
          command: preview
          stack-name: prod
          work-dir: deployments/pulumi

      - uses: pulumi/actions@v3
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        with:
          command: up
          stack-name: prod
          work-dir: deployments/pulumi
