name: Update pulumi stack
on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  pulumi:
    name: Run pulumi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install asdf
        uses: asdf-vm/actions/setup@v1
      - name: Install asdf tools
        run: |
          ./asdf.sh

      - name: Login to EKS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-west-2
        run: |
          aws eks update-kubeconfig --name usw2-r

      - uses: pulumi/actions@v3
        if: github.event_name == 'pull_request'
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-west-2
        with:
          command: preview
          stack-name: prod
          work-dir: deployments/pulumi

      - uses: pulumi/actions@v3
        if: github.event_name == 'push'
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-west-2
        with:
          command: up
          stack-name: prod
          work-dir: deployments/pulumi
