name: "Update README"
on:
  push:
    branches:
      - main
    paths:
      - .tool-versions

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update generated README sections
        run: |
          ./scripts/update_readme.sh
      - uses: EndBug/add-and-commit@v7
        with:
          add: "README.md"
          default_author: github_actions
          message: "Updating auto-gen docs in README"
